$engine: 3
$onesync: on

name: Cyberpunk
version: v0.1
author: mysty
description: A cyberpunk themed server for FiveM.

tasks:
  # Download default CFX resources first
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources

  # Download server.cfg and logo
  - action: ensure_dir
    path: ./tmp/

  - action: download_github
    src: https://github.com/mystyleigh/cp_recipe
    dest: ./tmp/cp_recipe

  - action: move_path
    src: ./tmp/cp_recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/cp_recipe/logo.png
    dest: ./logo.png
    
  # Download our custom resources
  - action: download_github
    src: https://github.com/mystyleigh/cp_resources
    dest: ./resources/[cyberpunk]
    
  # Used for sql database
  - action: download_github
    src: https://github.com/brouznouf/fivem-mysql-async
    ref: c5fa317a65acfe2eef453257e19e3b4fde137089
    dest: ./resources/mysql-async
    
  - action: remove_path
    path: ./tmp
